import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import localAuthRouter from "./local-auth";
import cafesRouter from "./cafes";
import menuRouter from "./menu";
import ordersRouter from "./orders";
import discoveryRouter from "./discovery";
import rewardsRouter from "./rewards";
import adminRouter from "./admin";
import addressesRouter from "./addresses";
import favoritesRouter from "./favorites";

const router: IRouter = Router();
router.use(healthRouter);
router.use(authRouter);
router.use(localAuthRouter);
router.use(cafesRouter);
router.use(menuRouter);
router.use(ordersRouter);
router.use(discoveryRouter);
router.use(rewardsRouter);
router.use(adminRouter);
router.use(addressesRouter);
export default router;